### ISSUE TITLE
Need help in using autofields (Example Code)

### ISSUE THREAD

**Issue by babsingh** [JustMaier/angular-autoFields-bootstrap#34]
Will it be possible for you to provide code for the example shown @ "http://justmaier.github.io/angular-autoFields-bootstrap/#demo" with dependencies? I am unable to incorporate dependencies for autofields properly.

**Comment by JustMaier** [comment]
@babsingh since this is closed, I assume you figured it out, right?

**Comment by babsingh** [comment]
yes
