### ISSUE TITLE
failed to instantiate?

### ISSUE THREAD

**Issue by Lighiche** [JustMaier/angular-autoFields-bootstrap#40]
Using MEAN.js after adding your modules to my bower.json and installing it, I required the file in my config/env/all.js under assets like all other third party modules.

'public/lib/angular-autoFields-bootstrap/autofields-bootstrap.js'

I added 'autofields' to my main app.module array. It obviously sees the file with the first line being 
angular.module('autofields.bootstrap', ['autofields.standard','ui.bootstrap']) as this is what it errors on. Can you tell me what's going on here by the looks of it those deps are registered to autofields at the bottom of the autofields-boostrap.js file. I have other third party modules installed that are injected no problem.

Uncaught Error: [$injector:modulerr] Failed to instantiate module mainTesting due to:
Error: [$injector:modulerr] Failed to instantiate module autofields due to:
Error: [$injector:modulerr] Failed to instantiate module autofields.bootstrap due to:
Error: [$injector:modulerr] Failed to instantiate module autofields.standard due to:
Error: [$injector:nomod] Module 'autofields.standard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

'public/lib/angular-autoFields-bootstrap/autofields.js' 

the app loads with this an i'm still testing but I am using bootstrap, I was under the impression that I needed to be using the -boostrap version.

**Comment by JustMaier** [comment]
Hi @Lighiche do you also have the reference to the following:

`public/lib/angular-autoFields-bootstrap/autofields.js`

**Comment by Lighiche** [comment]
Like I said I have the app loading with autofields.js but not the bookstrap version I wasn't sure if I was supposed to include both scripts or just one. I am using bootstrap in my app, I assumed the autofields-bootstrap.js was required to add styles to my forms.

**Comment by JustMaier** [comment]
If you want to use bootstrap styling you need to use both. From the error, it looks like `autofields.js` wasn't included.

**Comment by BartoGabriel** [comment]
I have the same problem.
The problem is that is not compatible with the new version of ui-bootstrap (> V1.0.0).
For release 0.14.0 we prefixed all our components.
https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

**Comment by BartoGabriel** [comment]
If you change the following line, you should fix the problem:
https://github.com/JustMaier/angular-autoFields-bootstrap/blob/master/autofields-bootstrap.js#L228

```javascript
	.config(['$tooltipProvider', function($tooltipProvider){
```
To:
```javascript
	.config(['$uibTooltipProvider', function($tooltipProvider){
```

**Comment by JustMaier** [comment]
Autofields has been updated to work with angular ui bootstrap v1.1.1
