### ISSUE TITLE
Dynamic validation

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [JustMaier/angular-autoFields-bootstrap#41]
Hi There, thanks for the wonderful library. One struggle I have a form, with a combo box, that upon selection shows and hides different fields in the form using `ngShow`. However these "dynamic" fields do have validation, so hidden fields also have to be valid upon form submitting. Is there any way, I can dynamically alter the `validation` option, and not just during build time? 
Thanks.

**Comment by JustMaier** [comment]
Hey @Dragomir-Ivanov, try using ngIf rather than ngShow/ngHide, that will make it so the "hidden" fields aren't required.

**Comment by Dragomir-Ivanov** [comment]
Thanks @JustMaier, works like a charm, didn't thought forms actually work on DOM. Still a newbie :)

**Comment by JustMaier** [comment]
Glad to hear that worked for you :)
