### ISSUE TITLE
How to set focus on first text box ?

### ISSUE THREAD

**Issue by Muqofa** [JustMaier/angular-autoFields-bootstrap#43]

**Comment by JustMaier** [comment]
I'm a little late to the party, but if you're still wondering how to do this, I'd suggest creating a directive that takes an attribute like `take-focus` and gives what ever element has that attribute focus. Then in the autofields schema you could just give a field the attr `'takeFocus': true`.

Let me know if you need more instructions.

**Comment by Muqofa** [comment]
Hello Just Maier,
Thank you for your suggest
Where is a take-focus directive example ? can you show me ?

But, how to make first textbox is default focus ?
so, i no need to add directive one by one.
