### ISSUE TITLE
Add multiple select boxes

### ISSUE THREAD

**Issue by adskiremote** [JustMaier/angular-autoFields-bootstrap#45]
Hi,

is it possible to add multiple select boxes and have the options inside the select box different each time (determined by what a user inputs via textboxes)?

I have this working but when I want to create more than 1 select box the values inside are always the same as each other.  Because  it uses the list:  'key as value for (key,value) in newDropbox'

Thanks

**Comment by JustMaier** [comment]
Hey @adskiremote, sorry for the delay on this. Still need help here? Can you maybe provide a snippet in plunker or something so that I can get an idea what you're trying to accomplish?

**Comment by adskiremote** [comment]
Hi @JustMaier thanks for getting back to me. I created my own autoFields mutator which works very well thank you.

I'll close this.  I have another issue which I'll create a new post for.  Odd mobile behaviour on dropdown boxes.
