### ISSUE TITLE
Datepicker compatibility

### ISSUE THREAD

**Issue by BartoGabriel** [JustMaier/angular-autoFields-bootstrap#47]
I have two warnings in console:
`uib-datepicker settings via uib-datepicker-popup attributes are deprecated and will be removed in UI Bootstrap 1.3, use datepicker-options attribute instead`
`angular.js:12722 uib-datepicker showWeeks attribute usage is deprecated, use datepicker-options attribute instead`

This is because I use UI Bootstrap 1.2.1.

This should be corrected in the lines of code:
https://github.com/JustMaier/angular-autoFields-bootstrap/blob/master/autofields-bootstrap.js#L48

This correction is not a priority. But if not corrected it will not work in UI Bootstrap 1.3.

**Comment by JustMaier** [comment]
Fixed :)
