### ISSUE TITLE
Date Options - ng-model-options timezone 

### ISSUE THREAD

**Issue by seigneur** [JustMaier/angular-autoFields-bootstrap#52]
Hi Thanks for the great module.

I had to tweak a little to set the timezone option for the datepicker

var inputAttrs = {
			+	ngModelOptions:"{timezone: 'utc'}",
				type:'text',
				uibDatepickerPopup: datepickerPopup,
				datepickerOptions: 'datepickerOptions',
				isOpen: '$property_cleanOpen'
			};
To autofields_bootstrap.js

from https://github.com/angular-ui/bootstrap/issues/4837
Is there a better way to do it?

**Comment by JustMaier** [comment]
Hey @seigneur you should be able to put that attribute in the field schema's attributes:

```
{ property: 'myDate', type: 'date', attr: { ngModelOptions: '{timezone: "utc"}' } }
```

**Comment by seigneur** [comment]
Thanks.
