### ISSUE TITLE
Odd mobile behaviour on dropdown boxes.  

### ISSUE THREAD

**Issue by adskiremote** [JustMaier/angular-autoFields-bootstrap#53]
Hi,

I'm getting some very strange behavior on mobiles with dropdown boxes.  If there is more than one dropdown in my autofields on mobile touch the select box is opening twice.  One over the top of each other.  So the first selection a user makes closes the dropdown selection options but nothing is actually selected.  Touch the select box again and it opens the selection options once, select the item and it shows selected in the dropdown.

I've tried to stop the issue by removing Bootstrap.js and only using angular-bootstrap.js but to no avail.  It improved the issue so wasn't happening so often but its still there.

Does anyone have any thoughts on what could be causing this?

**Comment by JustMaier** [comment]
Hey @adskiremote I know this is super delayed, but if this is still an issue, would you mind sharing some of your code so I can see what might be the problem?

**Comment by adskiremote** [comment]
Hi @JustMaier thanks for getting back to me.  I was sort of able to isolate the issue.  At least to the fact that when the form was taken out of a bootstrap modal and placed inline on the page these problems seem to go away.  I don't think it's an issue with yours then - quite possibly just to do with bootstrap.

**Comment by JustMaier** [comment]
Ok, I'm going to close this issue then, but feel free to reopen it if you have any problems
