### ISSUE TITLE
Custom attributes option not working

### ISSUE THREAD

**Issue by aks0020** [JustMaier/angular-autoFields-bootstrap#54]
I want to add `ngClick` attribute to container so passed this to `options` like this:
```
this.options = {
   			classes: {
   				container: ['form-group', 'form-field-container']
   			},
			attributes: {
				container: {
					'ngClick': 'createForm.selectField($event)'
				}
			}
   		};
```

But it does not add `ngClick` to the container it only adds custom classes.
I have also tried same with label but not working.
I am using version `2.2.2` from npm with angular `1.5.6`.

**Comment by aks0020** [comment]
Fixed by changing `getFieldContainer` line 76 to this:
`attrs = angular.extend({}, (directive.options.attributes.container || autofields.settings.attributes.container), attrs);
`
Same for label & input, don't know if this is the best way but fixes the issue.

**Comment by JustMaier** [comment]
Fixed. Thanks for passing that along
