### ISSUE TITLE
Use `xs` instead of `sm` columns.

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [JustMaier/angular-autoFields-bootstrap#59]
Hi threre,
Can you add an option that allows to use `xs`(or any other bootstrap supported column type) instead of `sm`. Thanks.

**Comment by JustMaier** [comment]
Hey @Dragomir-Ivanov you can override the default bootstrap column classes using the options.

```js
$scope.options = {
  classes: {
    col: ['col-xs-$size'],
    colOffset: ['col-xs-offset-$size']
  }
};
```

See a more complete example here: [http://codepen.io/anon/pen/eBMGNB](http://codepen.io/anon/pen/eBMGNB)

**Comment by Dragomir-Ivanov** [comment]
Thank you @JustMaier. It was not very obvious from the documentation. Much appreciated :)
