### ISSUE TITLE
How to include ng click event to a field

### ISSUE THREAD

**Issue by rchumacero** [JustMaier/angular-autoFields-bootstrap#61]
Hi there, that is not an issue just a simple question.

How can I define a ng click for a field? I didn't found in the documentation.

Thanks a lot if someone can help me.

**Comment by JustMaier** [comment]
Hey @rchumacero, you can use the `attr` option to set any attributes on the field. For example:

```js
{ property: 'thing', attr: { ngClick: 'alert()' }}
```
