### ISSUE TITLE
bower.json has been removed, breaking grunt builds

### ISSUE THREAD

**Issue by Vincent14** [JustMaier/angular-autoFields-bootstrap#66]
I can see the commit 756135ddc093534a9590f21ed30ac2047019b046 is removing the bower.json file, this file is required to build legacy projects with tools like grunt. This file is designed for tooling, so could you bring it back in master?

Best regards

**Comment by JustMaier** [comment]
Fixed :)

**Comment by Vincent14** [comment]
Awesome reactivity, no need to pull request so! Thank you very much!
